[mypy]
python_version = 3.10
ignore_missing_imports = True
follow_imports = normal
show_error_codes = True
warn_return_any = True
disallow_untyped_defs = False
namespace_packages = True
explicit_package_bases = True

[mypy-database.*]
ignore_missing_imports = True

[mypy-project_management.*]
ignore_missing_imports = True

[mypy-api_gateway.*]
ignore_missing_imports = True

[mypy-auth_service.*]
ignore_missing_imports = True

[mypy-*.routes.*]
ignore_missing_imports = False
disallow_untyped_defs = False

